### ISSUE TITLE
Adding a "play from start" option would resolve the non-intuitive way "play" works

### ISSUE THREAD

**Issue by ShiCheng-Lu** [MajestikButter/Cinematic-Cameras-V2#2]
one would expect play to play the cinematic camera, maybe add a play from start stick that plays from the start, then play would make sense to play from cursor location. You can also rename play to play from cursor and that will provide more info to the user.

**Comment by MajestikButter** [comment]
renamed to "Play Cinematic from Cursor" in 1.3.0
